//import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";
import "./ui/globals.css";
import { publicSans } from "./ui/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
